export interface JttIconMetadata {
  name: string;
  title: string;
  category: string;
  tags: string[];
  aliases: string[];
  contexts: string[];
  related: string[];
  accessibility: { default: "decorative" | "meaningful" | "interactive" | "status" | "brand" };
  path: string;
  family: "line";
}
export interface JttIconModule {
  name: string;
  title: string;
  category: string;
  svg: string;
  metadata: JttIconMetadata;
}
export declare const apple: JttIconModule;
export declare const archive: JttIconModule;
export declare const arrowDown: JttIconModule;
export declare const arrowDownLeft: JttIconModule;
export declare const arrowDownRight: JttIconModule;
export declare const arrowLeft: JttIconModule;
export declare const arrowRight: JttIconModule;
export declare const arrowUp: JttIconModule;
export declare const arrowUpLeft: JttIconModule;
export declare const arrowUpRight: JttIconModule;
export declare const attachment: JttIconModule;
export declare const bag: JttIconModule;
export declare const bell: JttIconModule;
export declare const bookmark: JttIconModule;
export declare const braces: JttIconModule;
export declare const bug: JttIconModule;
export declare const calendar: JttIconModule;
export declare const camera: JttIconModule;
export declare const cart: JttIconModule;
export declare const check: JttIconModule;
export declare const chevronDown: JttIconModule;
export declare const chevronLeft: JttIconModule;
export declare const chevronRight: JttIconModule;
export declare const chevronUp: JttIconModule;
export declare const clipboard: JttIconModule;
export declare const clock: JttIconModule;
export declare const code: JttIconModule;
export declare const copy: JttIconModule;
export declare const creditCard: JttIconModule;
export declare const database: JttIconModule;
export declare const iconDelete: JttIconModule;
export declare const discord: JttIconModule;
export declare const document: JttIconModule;
export declare const download: JttIconModule;
export declare const edit: JttIconModule;
export declare const error: JttIconModule;
export declare const eye: JttIconModule;
export declare const file: JttIconModule;
export declare const fileMinus: JttIconModule;
export declare const filePlus: JttIconModule;
export declare const filter: JttIconModule;
export declare const folder: JttIconModule;
export declare const folderOpen: JttIconModule;
export declare const folderPlus: JttIconModule;
export declare const gitBranch: JttIconModule;
export declare const gitCommit: JttIconModule;
export declare const gitMerge: JttIconModule;
export declare const github: JttIconModule;
export declare const heart: JttIconModule;
export declare const help: JttIconModule;
export declare const home: JttIconModule;
export declare const image: JttIconModule;
export declare const info: JttIconModule;
export declare const link: JttIconModule;
export declare const loading: JttIconModule;
export declare const location: JttIconModule;
export declare const lock: JttIconModule;
export declare const mail: JttIconModule;
export declare const map: JttIconModule;
export declare const menu: JttIconModule;
export declare const message: JttIconModule;
export declare const mic: JttIconModule;
export declare const minus: JttIconModule;
export declare const music: JttIconModule;
export declare const pause: JttIconModule;
export declare const play: JttIconModule;
export declare const playCircle: JttIconModule;
export declare const plus: JttIconModule;
export declare const receipt: JttIconModule;
export declare const redo: JttIconModule;
export declare const refresh: JttIconModule;
export declare const rocket: JttIconModule;
export declare const save: JttIconModule;
export declare const search: JttIconModule;
export declare const send: JttIconModule;
export declare const server: JttIconModule;
export declare const settings: JttIconModule;
export declare const share: JttIconModule;
export declare const sort: JttIconModule;
export declare const star: JttIconModule;
export declare const stop: JttIconModule;
export declare const success: JttIconModule;
export declare const sun: JttIconModule;
export declare const tag: JttIconModule;
export declare const terminal: JttIconModule;
export declare const undo: JttIconModule;
export declare const unlock: JttIconModule;
export declare const upload: JttIconModule;
export declare const user: JttIconModule;
export declare const userCircle: JttIconModule;
export declare const userMinus: JttIconModule;
export declare const userPlus: JttIconModule;
export declare const users: JttIconModule;
export declare const video: JttIconModule;
export declare const volume: JttIconModule;
export declare const volumeOff: JttIconModule;
export declare const warning: JttIconModule;
export declare const x: JttIconModule;
export declare const xTwitter: JttIconModule;
export declare const youtube: JttIconModule;
export declare const iconNames: readonly string[];
export declare const icons: Record<string, JttIconModule>;
